const express = require('express')
const router = express.Router()
const passport = require(__base + '/config/passport')

const login = require('./handlers/auth/handlerLogin')
const register = require('./handlers/auth/handlerRegister')
const getUserId = require('./handlers/user/handlerGetUserId')
const getUser = require('./handlers/user/handlerGetUser')
const newContact = require('./handlers/contact/handlerNewContact')
const updateContact = require('./handlers/contact/handlerUpdateContact')
const removeContact = require('./handlers/contact/handlerRemoveContact')
const getContacts = require('./handlers/contacts/handlerGetContacts')
const getContactsById = require('./handlers/contacts/handlerGetContactsByUserId')

router.post('/auth/login/', passport.authenticate('local', { session: false }), login)
router.post('/auth/register/', register)
router.get('/user/:username', passport.authenticate('jwt', { session: false }), getUserId)
router.get('/user/id/:userId', passport.authenticate('jwt', { session: false }), getUser)
router.post('/contact/:username', passport.authenticate('jwt', { session: false }), newContact)
router.post('/contact/privacy/:username', passport.authenticate('jwt', { session: false }), updateContact)
router.put('/contact/:username', passport.authenticate('jwt', { session: false }), removeContact)
router.get('/contacts/name/:username', passport.authenticate('jwt', { session: false }), getContacts)
router.get('/contacts/id/:userId', passport.authenticate('jwt', { session: false }), getContactsById)

module.exports = router
