const express = require('express')
const router = express.Router()
const passport = require(__base + '/config/passport')

const login = require('./handlers/auth/handlerLogin')
const register = require('./handlers/auth/handlerRegister')
const getUserId = require('./handlers/user/handlerGetUserId')
const getUser = require('./handlers/user/handlerGetUser')
const newContact = require('./handlers/contact/handlerNewContact')
const updateContact = require('./handlers/contact/handlerUpdateContact')
const removeContact = require('./handlers/contact/handlerRemoveContact')
const getContacts = require('./handlers/contacts/handlerGetContacts')
const getContactsById = require('./handlers/contacts/handlerGetContactsByUserId')

router.post('/auth/login/', passport.authenticate('local', { session: false }), login)
router.post('/auth/register/', register)
router.get('/user/:username', getUserId)
router.get('/user/id/:userId', getUser)
router.post('/contact/:username', newContact)
router.post('/contact/privacy/:username', updateContact)
router.delete('/contact/:id', removeContact)
router.get('/contacts/name/:username', getContacts)
router.get('/contacts/id/:userId', getContactsById)

module.exports = router
